// import type { Metadata } from "next";

// import "./globals.css";



// export const metadata: Metadata = {
//   title: "Test-task",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
        
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


import './globals.css';
import { AuthProvider } from '../context/AuthContext';

export const metadata = {
  title: 'My App',
  description: 'Next.js App with JWT Auth',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
